<?php

namespace BestDeal\MainBundle\Repository;

/**
 * AdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAds () {
        $q = $this->getEntityManager()->createQuery('
        SELECT a FROM BestDealMainBundle:Ad a ORDER BY a.createdAt DESC');
        return $q->getResult();
    }
}
